Spectrum-CETB/Spectober_Fest

- README.md
* Hardware:
* Toolchain:
* SDK:
> Pull request template check

- projects_Intermediate/WEB_DEVELOPEMENT/PrimeFactorCalc_Jeevan-Alok/README.md
- projects_Intermediate/WEB_DEVELOPEMENT/PrimeFactorCalc_Jeevan-Alok/index.html
- projects_Intermediate/WEB_DEVELOPEMENT/PrimeFactorCalc_Jeevan-Alok/script.js
- projects_Intermediate/WEB_DEVELOPEMENT/PrimeFactorCalc_Jeevan-Alok/style.css
Made a Prime factor calculator app using **Sieve of Eratosthenes** to calculate prime factors in **O(n log log n)** time complexity assuming worst case scenario. User input would be taken and factors would be calculated.
* Hardware:
* Toolchain:
* SDK:
Code made under Hactoberfest'22
> Prime Factor Calculator

- projects_Intermediate/Project_Domain.md
Updated Python Project List and Web Dev Project List
Added the suggested projects for Python and Web Development
Readme Documentation
- [] My code follows the style guidelines of this project
> Updated Readme

- projects_Intermediate/PYTHON_DEVELOPMENT/UltimatePdfMaker_Sattwik-Palai/The_ultimate_pdf_maker.py
This is a python script that scans every image in a directory, and then converts the required one as suggested by the user to convert it into Pdfs. It has further option to merge those files into a single Pdf and in any particular order prescribed by the user
* Firmware version: Python 3.0
* Hardware:
* Toolchain:
* SDK:
> Added PdfMaker File

- projects_Intermediate/PYTHON_DEVELOPMENT/RockPaperScissors_Kalinga-Khatua/Readme.md
- projects_Intermediate/PYTHON_DEVELOPMENT/RockPaperScissors_Kalinga-Khatua/rpsGame.py
This is a python program you can use to play Rock, Paper, Scissor on the Command Line.<br>
Simply choose the number of turns and you're ready to go.
* Firmware version: Python 3.10.6
* Hardware:
* Toolchain:
* SDK:
> Added Rock Paper Scissor game.

- coding_freshmen/PYTHON/VINWARE/MAXIMUM_SUM.py
- coding_freshmen/PYTHON/VINWARE/README.md
Solved the MAXIMUM_SUM problem in Python
> Python solution for Maximum_sum

- coding_freshmen/C++/Prateek_Rath/MAJORITY_ELEMENT.cpp
- coding_freshmen/C++/Prateek_Rath/README.md
Solution to the problem majority element with best case space optimization in O(1)
> Solution to majority element

- coding_freshmen/C++/Kumar_Santosh/MAXIMUM_SUM.cpp
- coding_freshmen/C++/Kumar_Santosh/README.md
SOLVED MAXIMUM_SUM problem in C++.
* Firmware version: C++ 17
* Hardware:
* Toolchain:
* SDK:
> Solving MAXIMUM_SUM problem using C++

- coding_freshmen/C++/Nitin_Mishra/ANAGRAM.cpp
- coding_freshmen/C++/Nitin_Mishra/PROFICIENT_TRADER.cpp
Some solution files were not present in the merge, adding them now
* Hardware:
* Toolchain:
* SDK:
> Re-Commit PR, Solutions in C++

- projects_Intermediate/WEB_DEVELOPEMENT/MorseTranslator_Jeevan-Alok/README.md
- projects_Intermediate/WEB_DEVELOPEMENT/MorseTranslator_Jeevan-Alok/app.js
- projects_Intermediate/WEB_DEVELOPEMENT/MorseTranslator_Jeevan-Alok/index.html
- projects_Intermediate/WEB_DEVELOPEMENT/MorseTranslator_Jeevan-Alok/style.css
A Morse translator that converts plain English to Morse code and vice versa
* Hardware:
* Toolchain:
* SDK:
> Morse Translator

- coding_freshmen/C/heySwayam/pattern_finder.c
- coding_freshmen/C/heySwayam/pattern_finder.md
* Hardware:
* Toolchain:
* SDK:
> Q.2 --> pattern_finder

- coding_freshmen/C++/Aniket_Tripathy/PRODUCT_FINDER.cpp
- coding_freshmen/C++/Aniket_Tripathy/README.md
Added C++ solution for the question product_finder
> C++ solution to Product_finder

- coding_freshmen/C++/Ashutosh_Panda/Readme.md
- coding_freshmen/C++/Ashutosh_Panda/SoErato.cpp
- coding_freshmen/C++/Ashutosh_Panda/spiral.cpp
> Files Committed

- coding_freshmen/JAVA/ABUZANAZAD/README.md
- coding_freshmen/JAVA/ABUZANAZAD/ROMAN_TO_DECIMAL.java
---
name: PR Template
about: Pull Request Template
title: 'ROMAN_TO_DECIMAL'
labels: hacktoberfest
assignees: ''
---
Roman numerals are usually written largest to smallest from left to right. However, the numeral for four is not IIII. Instead, the number four is written as IV. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as IX. There are six instances where subtraction is used:
* Hardware:
* Toolchain:
* SDK:
> Roman to Decimal java solution

- coding_freshmen/C++/Liza_Patra/README.md
- coding_freshmen/C++/Liza_Patra/Sort_array.cpp
* Hardware:
* Toolchain:
* SDK:
> sort_array

- coding_freshmen/C++/Kumar_Santosh/README.md
- coding_freshmen/C++/Kumar_Santosh/SORT_01-KS.cpp
---
name: PR Template
about: Pull Request Template
title: ''
labels: hacktoberfest
assignees: ''
---
SOLVED the problem SORT_01
* Firmware version: C++ 17
* Hardware:
* Toolchain:
* SDK:
- [ .] My code follows the style guidelines of this project
> SOLVED SORT_01 problem using C++

- coding_freshmen/JAVA/Soumyaranjan/MAJORITY_ELEMENT.java
- coding_freshmen/JAVA/Soumyaranjan/readme.md
Solved MAJORITY_ELEMENT using java.
Given an array nums of size n, return the majority element.
> Majority Element solved using java

- projects_Intermediate/PYTHON_DEVELOPMENT/ChatApp_Siddhartha-Shankar-Padhy/README.md
- projects_Intermediate/PYTHON_DEVELOPMENT/ChatApp_Siddhartha-Shankar-Padhy/chatServer.py
- projects_Intermediate/PYTHON_DEVELOPMENT/ChatApp_Siddhartha-Shankar-Padhy/main.py
A network application built with socket and tkinter in python. Both the dependencies are provided inbuilt with python.
* Hardware:
* Toolchain:
* SDK:
> ChatApp(Socket programming)

- projects_Intermediate/PYTHON_DEVELOPMENT/Typing_Speed_Calculator-Kumar_Santosh/Readme.md
- projects_Intermediate/PYTHON_DEVELOPMENT/Typing_Speed_Calculator-Kumar_Santosh/typing_speed.py
This is a Python project for Calculating Keyboard Typing Speed. 
After typing through each letter correctly it will show your typing speed in WPM(words per minute) in the end.
Do Give It A Try!! 
* Firmware version: Python 3.10
* Hardware:
* Toolchain:
* SDK:
> Added TYPING SPEED Calculator Python Project

- coding_freshmen/C++/Binay_Sahu/MAXIMUM_SUM.cpp
- coding_freshmen/C++/Binay_Sahu/README.md
Added C++ solution to the question maximum sum.
> Added C++ solution to Maximum_Sum

- coding_freshmen/PYTHON/root_user/ROMAN_TO_DECIMAL.cpp
* Hardware:
* Toolchain:
* SDK:
> final commit

- coding_freshmen/C++/Binay_Sahu/ANAGRAMS.cpp
- coding_freshmen/C++/Binay_Sahu/README.md
Added C++ solution to the problem Anagrams
> C++ Solution to Anagrams

- coding_freshmen/C++/root_user/PRODUCT_FINDER.cpp
- coding_freshmen/PYTHON/root_user/PRODUCT_FINDER.cpp
* Hardware:
* Toolchain:
* SDK:
> PRODUCT_FINDER

- projects_Intermediate/PYTHON_DEVELOPMENT/whatsapp_chat_analyzer_pratyush-giri/README.md
- projects_Intermediate/PYTHON_DEVELOPMENT/whatsapp_chat_analyzer_pratyush-giri/app.py
- projects_Intermediate/PYTHON_DEVELOPMENT/whatsapp_chat_analyzer_pratyush-giri/helper.py
- projects_Intermediate/PYTHON_DEVELOPMENT/whatsapp_chat_analyzer_pratyush-giri/preprocessor.py
* Hardware:
* Toolchain:
* SDK:
> whatsapp chat analyzer project

- projects_Intermediate/WEB_DEVELOPEMENT/ToDoList_SoumyaSuman/README.md
- projects_Intermediate/WEB_DEVELOPEMENT/ToDoList_SoumyaSuman/index.html
- projects_Intermediate/WEB_DEVELOPEMENT/ToDoList_SoumyaSuman/logic.js
- projects_Intermediate/WEB_DEVELOPEMENT/ToDoList_SoumyaSuman/style.css
* Hardware:
* Toolchain:
* SDK:
> TODO_Soumya_Suman

- projects_Intermediate/WEB_DEVELOPEMENT/deadjokes_Prasannajeet-Pradhan/README.md
- projects_Intermediate/WEB_DEVELOPEMENT/deadjokes_Prasannajeet-Pradhan/index.html
- projects_Intermediate/WEB_DEVELOPEMENT/deadjokes_Prasannajeet-Pradhan/script.js
- projects_Intermediate/WEB_DEVELOPEMENT/deadjokes_Prasannajeet-Pradhan/style.css
* Hardware:
* Toolchain:
* SDK:
> dadjokes for hactoberfest

- coding_freshmen/C++/SURAJ_SHARMA/Allocate_minimum_number_of_pages.cpp
- coding_freshmen/C++/SURAJ_SHARMA/Clone_a_LL.cpp
- coding_freshmen/C++/SURAJ_SHARMA/Count_inversions.cpp
- coding_freshmen/C++/SURAJ_SHARMA/README.md
* Hardware:
* Toolchain:
* SDK:
> ADDED_CP_QUESTIONS_SURAJ_SHARMA

- projects_Intermediate/WEB_DEVELOPEMENT/simpleCalculator_Prasannajeet-Pradhan/README.md
- projects_Intermediate/WEB_DEVELOPEMENT/simpleCalculator_Prasannajeet-Pradhan/index.html
- projects_Intermediate/WEB_DEVELOPEMENT/simpleCalculator_Prasannajeet-Pradhan/script.js
- projects_Intermediate/WEB_DEVELOPEMENT/simpleCalculator_Prasannajeet-Pradhan/style.css
- projects_Intermediate/WEB_DEVELOPEMENT/todo_Prasannajeet-Pradhan/README.md
- projects_Intermediate/WEB_DEVELOPEMENT/todo_Prasannajeet-Pradhan/index.html
- projects_Intermediate/WEB_DEVELOPEMENT/todo_Prasannajeet-Pradhan/script.js
- projects_Intermediate/WEB_DEVELOPEMENT/todo_Prasannajeet-Pradhan/style.css
* Hardware:
* Toolchain:
* SDK:
> Simple Calculator for hacktoberfest

- coding_freshmen/C++/SURAJ_SHARMA_COMMIT_2/Remove_Loop_LL.cpp
- coding_freshmen/C++/SURAJ_SHARMA_COMMIT_2/TRAPPING_RAIN_WATER.cpp
- coding_freshmen/C++/SURAJ_SHARMA_COMMIT_2/readme.txt
* Hardware:
* Toolchain:
* SDK:
> ADDED_CP_qsns_SURAJ_SHARMA_2

- coding_freshmen/C++/SURAJ_SHARMA_COMMIT_3/FIND_ALL_FOUR_SUM_NUMBERS.cpp
- coding_freshmen/C++/SURAJ_SHARMA_COMMIT_3/README.txt
- coding_freshmen/C++/SURAJ_SHARMA_COMMIT_3/SPIRALLY_TRAVERSING_a_matrix.cpp
- coding_freshmen/C++/SURAJ_SHARMA_COMMIT_4/K-th_Element_of_TWO_SORTED_ARRAYS.cpp
- coding_freshmen/C++/SURAJ_SHARMA_COMMIT_4/Majority_Element.cpp
- coding_freshmen/C++/SURAJ_SHARMA_COMMIT_4/README.txt
* Hardware:
* Toolchain:
* SDK:
> CP_QUESTIONS_ADDED_3_SURAJ_SHARMA

- projects_Intermediate/WEB_DEVELOPEMENT/digitalClock_Aditya-Aswajeet-Nayak/README.md
- projects_Intermediate/WEB_DEVELOPEMENT/digitalClock_Aditya-Aswajeet-Nayak/index.html
- projects_Intermediate/WEB_DEVELOPEMENT/digitalClock_Aditya-Aswajeet-Nayak/index.js
- projects_Intermediate/WEB_DEVELOPEMENT/digitalClock_Aditya-Aswajeet-Nayak/style.css
* Hardware:
* Toolchain:
* SDK:
> Digital Clock

- projects_Intermediate/WEB_DEVELOPEMENT/calculator_Aditya-Aswajeet-Nayak/README.md
- projects_Intermediate/WEB_DEVELOPEMENT/calculator_Aditya-Aswajeet-Nayak/index.html
- projects_Intermediate/WEB_DEVELOPEMENT/calculator_Aditya-Aswajeet-Nayak/index.js
- projects_Intermediate/WEB_DEVELOPEMENT/calculator_Aditya-Aswajeet-Nayak/style.css
* Hardware:
* Toolchain:
* SDK:
> Simple Calculator

- projects_Intermediate/WEB_DEVELOPEMENT/socialMediaMenu-Aditya-Aswajeet-Nayak/README.md
- projects_Intermediate/WEB_DEVELOPEMENT/socialMediaMenu-Aditya-Aswajeet-Nayak/index.html
- projects_Intermediate/WEB_DEVELOPEMENT/socialMediaMenu-Aditya-Aswajeet-Nayak/index.js
- projects_Intermediate/WEB_DEVELOPEMENT/socialMediaMenu-Aditya-Aswajeet-Nayak/style.css
* Hardware:
* Toolchain:
* SDK:
> Social Media Menu

- coding_freshmen/C++/Sunita_Bal 1/Max_rectangle.cpp
- coding_freshmen/C++/Sunita_Bal 1/README.txt
- coding_freshmen/C++/Sunita_Bal 1/The_Painter's_Partition_Problem-II.cpp
* Hardware:
* Toolchain:
* SDK:
> Cp_Questions_1

- coding_freshmen/C++/SURAJ_SHARMA_COMMIT_5/CIRCULAR_TOUR.cpp
- coding_freshmen/C++/SURAJ_SHARMA_COMMIT_5/README.txt
- coding_freshmen/C++/SURAJ_SHARMA_COMMIT_5/THE_CELEBRITY_PROBLEM.cpp
* Hardware:
* Toolchain:
* SDK:
> CP_QUESN_ADDED_5_SURAJ_SHARMA

- projects_Intermediate/WEB_DEVELOPEMENT/budget-Tracker_Pallavi-Mahapatra/README.md
- projects_Intermediate/WEB_DEVELOPEMENT/budget-Tracker_Pallavi-Mahapatra/index.html
- projects_Intermediate/WEB_DEVELOPEMENT/budget-Tracker_Pallavi-Mahapatra/index.js
- projects_Intermediate/WEB_DEVELOPEMENT/budget-Tracker_Pallavi-Mahapatra/style.css
Added an intermediate project.
* Hardware:
* Toolchain:
* SDK:
> Budget Tracker Project

- projects_Intermediate/PYTHON_DEVELOPMENT/PingPong_SoumyaSuman/README.md
- projects_Intermediate/PYTHON_DEVELOPMENT/PingPong_SoumyaSuman/main.py
* Hardware:
* Toolchain:
* SDK:
> PingPong_SoumyaSuman

- coding_freshmen/C++/sunita_bal_2/README.txt
- coding_freshmen/C++/sunita_bal_2/Rat_in_a_Maze_Problem - I.cpp
- coding_freshmen/C++/sunita_bal_2/The_Celebrity_Problem.cpp
* Hardware:
* Toolchain:
* SDK:
> cp_questions_2

- projects_Intermediate/WEB_DEVELOPEMENT/PROFILE-CARD_PALLAVI-MAHAPATRA/README.md
- projects_Intermediate/WEB_DEVELOPEMENT/PROFILE-CARD_PALLAVI-MAHAPATRA/bootstrap.css
- projects_Intermediate/WEB_DEVELOPEMENT/PROFILE-CARD_PALLAVI-MAHAPATRA/index.html
- projects_Intermediate/WEB_DEVELOPEMENT/PROFILE-CARD_PALLAVI-MAHAPATRA/profile.js
- projects_Intermediate/WEB_DEVELOPEMENT/PROFILE-CARD_PALLAVI-MAHAPATRA/style.css
- projects_Intermediate/WEB_DEVELOPEMENT/budget-Tracker_Pallavi-Mahapatra/index.html
Added a new project.
* Hardware:
* Toolchain:
* SDK:
> Profile Card

- projects_Intermediate/WEB_DEVELOPEMENT/Moviepedia_Pallavi-Mahapatra/README.md
- projects_Intermediate/WEB_DEVELOPEMENT/Moviepedia_Pallavi-Mahapatra/bootstrap.css
- projects_Intermediate/WEB_DEVELOPEMENT/Moviepedia_Pallavi-Mahapatra/index.html
- projects_Intermediate/WEB_DEVELOPEMENT/Moviepedia_Pallavi-Mahapatra/movie.js
- projects_Intermediate/WEB_DEVELOPEMENT/Moviepedia_Pallavi-Mahapatra/style2.css
* Hardware:
* Toolchain:
* SDK:
> Moviepedia

- coding_freshmen/C++/Sunita_bal_3/Allocate_minimum_number_of_pages.cpp
- coding_freshmen/C++/Sunita_bal_3/README.txt
- coding_freshmen/C++/Sunita_bal_3/Trapping_Rain_Water.cpp
* Hardware:
* Toolchain:
* SDK:
> CP_questions_3

- coding_freshmen/C/dfs_prajwal-behera/dfs.c
* Hardware:
* Toolchain:
* SDK:
> dfs c code

- coding_freshmen/C/djisktra_prajwal-behera/djisktra.c
- coding_freshmen/C/floyd warshall_prajwal-behera/floyd warshall.c
* Hardware:
* Toolchain:
* SDK:
> djjsktra c code

- coding_freshmen/C/floydWarshall_Prajwal-Behera/floyd_warshall.c
* Hardware:
* Toolchain:
* SDK:
> floydWarshall c code prajwal B

- coding_freshmen/C/heapsort_prajwal-behera/heapsort.c
* Hardware:
* Toolchain:
* SDK:
> heapsort c code prajwal

- projects_Intermediate/PYTHON_DEVELOPMENT/snakes_and_ladder_subhasish-pattanaik/.idea/.gitignore
- projects_Intermediate/PYTHON_DEVELOPMENT/snakes_and_ladder_subhasish-pattanaik/.idea/inspectionProfiles/Project_Default.xml
- projects_Intermediate/PYTHON_DEVELOPMENT/snakes_and_ladder_subhasish-pattanaik/.idea/inspectionProfiles/profiles_settings.xml
- projects_Intermediate/PYTHON_DEVELOPMENT/snakes_and_ladder_subhasish-pattanaik/.idea/misc.xml
- projects_Intermediate/PYTHON_DEVELOPMENT/snakes_and_ladder_subhasish-pattanaik/.idea/modules.xml
- projects_Intermediate/PYTHON_DEVELOPMENT/snakes_and_ladder_subhasish-pattanaik/.idea/snakes&ladder.iml
- projects_Intermediate/PYTHON_DEVELOPMENT/snakes_and_ladder_subhasish-pattanaik/README.md
- projects_Intermediate/PYTHON_DEVELOPMENT/snakes_and_ladder_subhasish-pattanaik/main.py
snake and ladder game
* Hardware:
* Toolchain:
* SDK:
> snake and ladder game using python

- coding_freshmen/C++/Sunita_bal_4/Clone_a_linked_list_with_next_and_random_pointer.cpp
- coding_freshmen/C++/Sunita_bal_4/README.txt
- coding_freshmen/C++/Sunita_bal_4/Spirally_traversing_a_matrix.cpp
- coding_freshmen/C++/Sunita_bal_cp4/Clone_a_linked_list_with_next_and_random_pointer.cpp
- coding_freshmen/C++/Sunita_bal_cp4/Kadane_algo.cpp
- coding_freshmen/C++/Sunita_bal_cp4/README.txt
- coding_freshmen/C++/Sunita_bal_cp4/Spirally_traversing_a_matrix.cpp
* Hardware:
* Toolchain:
* SDK:
> CP_Question_4_

- coding_freshmen/C++/TANIKA_GULATI/README.md
- coding_freshmen/C++/TANIKA_GULATI/SORT_01.cpp
* Hardware:
* Toolchain:
* SDK:
> Solved sort_01
